# Generated by Django 4.0.1 on 2022-03-18 05:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contenido',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(default=None),
        ),
    ]
