# Generated by Django 4.0.1 on 2022-03-17 00:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menuApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostgresConfig',
            new_name='Post',
        ),
        migrations.RenameModel(
            old_name='PersonasappConfig',
            new_name='Profile',
        ),
    ]
